version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    # Core linters - bugs and potential issues
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Style
    - misspell

  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    misspell:
      locale: US

    staticcheck:
      checks:
        - all
        - -SA1019  # Disable deprecation warnings
        - -QF1008  # Disable "could remove embedded field" suggestions

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - vendor
      - third_party
      - ".*\\.pb\\.go$"
      - ".*\\.gen\\.go$"

formatters:
  enable:
    - gofmt
    - goimports
